Controllers/ExamMarksTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseAccess;

namespace University_Mangement_System.Controllers
{
    public class ExamMarksTablesController : Controller
    {
        private UniversityMgtDbEntities db = new UniversityMgtDbEntities();

        // GET: ExamMarksTables
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

           
            var examMarksTables = db.ExamMarksTables.Include(e => e.ClassSubjectTable).Include(e => e.ExamTable).Include(e => e.StudentTable).Include(e => e.UserTable).OrderByDescending(e => e.MarksID);
            return View(examMarksTables.ToList());
        }

        // GET: ExamMarksTables/Details/5
        public ActionResult Details(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

   
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamMarksTable examMarksTable = db.ExamMarksTables.Find(id);
            if (examMarksTable == null)
            {
                return HttpNotFound();
            }
            return View(examMarksTable);
        }

        // GET: ExamMarksTables/Create
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

         
            ViewBag.ClassSubjectID = new SelectList(db.ClassSubjectTables, "ClassSubjectID", "Name");
            ViewBag.ExamID = new SelectList(db.ExamTables, "ExamID", "Title");
            ViewBag.StudentID = new SelectList(db.StudentTables, "StudentID", "Name");
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName");
            return View();
        }

        public ActionResult GetByPromotID(string sid)
        {
            int promoteid = Convert.ToInt32(sid);
            var promoterecord = db.StudentPromotTables.Find(promoteid);
            List<StudentTable> stdlist = new List<StudentTable>();
            stdlist.Add(new StudentTable { StudentID = promoterecord.StudentID, Name = promoterecord.StudentTable.Name });
            //var student = promoterecord.StudentTable.Name;
            List<ClassSubjectTable> listsubjects = new List<ClassSubjectTable>();
            var classsubjects = db.ClassSubjectTables.Where(cls => cls.ClassID == promoterecord.ClassID && cls.IsActive == true);
            foreach (var subj in classsubjects)
            {
                listsubjects.Add(new ClassSubjectTable { ClassSubjectID = subj.ClassSubjectID, Name = subj.Name});
            }
            return Json(new { std = stdlist, subjects = listsubjects }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTotalMarks(string sid)
        {
            int classsubjectid = Convert.ToInt32(sid);
            var totalmarks = db.ClassSubjectTables.Find(classsubjectid).SubjectTable.TotalMarks;
            return Json(new { data = totalmarks}, JsonRequestBehavior.AllowGet);
        }

        // POST: ExamMarksTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExamMarksTable examMarksTable)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            examMarksTable.UserID = userid;
            if (ModelState.IsValid)
            {
                db.ExamMarksTables.Add(examMarksTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClassSubjectID = new SelectList(db.ClassSubjectTables, "ClassSubjectID", "Name", examMarksTable.ClassSubjectID);
            ViewBag.ExamID = new SelectList(db.ExamTables, "ExamID", "Title", examMarksTable.ExamID);
            ViewBag.StudentID = new SelectList(db.StudentTables, "StudentID", "Name", examMarksTable.StudentID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", examMarksTable.UserID);
            return View(examMarksTable);
        }

        // GET: ExamMarksTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

       
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamMarksTable examMarksTable = db.ExamMarksTables.Find(id);
            if (examMarksTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClassSubjectID = new SelectList(db.ClassSubjectTables, "ClassSubjectID", "Name", examMarksTable.ClassSubjectID);
            ViewBag.ExamID = new SelectList(db.ExamTables, "ExamID", "Title", examMarksTable.ExamID);
            ViewBag.StudentID = new SelectList(db.StudentTables, "StudentID", "Name", examMarksTable.StudentID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", examMarksTable.UserID);
            return View(examMarksTable);
        }

        // POST: ExamMarksTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExamMarksTable examMarksTable)
        {
            
            if (ModelState.IsValid)
            {
                db.Entry(examMarksTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClassSubjectID = new SelectList(db.ClassSubjectTables, "ClassSubjectID", "Name", examMarksTable.ClassSubjectID);
            ViewBag.ExamID = new SelectList(db.ExamTables, "ExamID", "Title", examMarksTable.ExamID);
            ViewBag.StudentID = new SelectList(db.StudentTables, "StudentID", "Name", examMarksTable.StudentID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", examMarksTable.UserID);
            return View(examMarksTable);
        }

        // GET: ExamMarksTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

          
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamMarksTable examMarksTable = db.ExamMarksTables.Find(id);
            if (examMarksTable == null)
            {
                return HttpNotFound();
            }
            return View(examMarksTable);
        }

        // POST: ExamMarksTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExamMarksTable examMarksTable = db.ExamMarksTables.Find(id);
            db.ExamMarksTables.Remove(examMarksTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ExamMarksTables/Create.cshtml
@model DatabaseAccess.ExamMarksTable

@{
    ViewBag.Title = "Create";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<div class="card mb-4 shadow">
    <div class="card-header"> <h4>Student Tution Fee</h4></div>

    <div class="card-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ExamMarksTable</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" ,@id = "StudentID" })
                    @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6">
                    <div class="row">
                        <input type="number" class="form-control" placeholder="Enter promote ID" id="promoteid" />

                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row">
                        <input type="button" class="btn btn-primary" value="Find" id="FindPromoteRecord" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ExamID, "ExamID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ExamID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ExamID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ClassSubjectID, "ClassSubjectID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ClassSubjectID", null, htmlAttributes: new { @class = "form-control", @id = "ClassSubjectID" })
                    @Html.ValidationMessageFor(model => model.ClassSubjectID, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.TotalMarks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TotalMarks, new { htmlAttributes = new { @class = "form-control", @id = "TotalMarks" } })
                    @Html.ValidationMessageFor(model => model.TotalMarks, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ObtainMarks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ObtainMarks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ObtainMarks, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {

        $('#FindPromoteRecord').click(function () {
            $('#ClassSubjectID').html('');
            $('#StudentID').html('');
            $.ajax({
                url: '@Url.Action("GetByPromotID", "ExamMarksTables")',
                type: 'GET',
                data: { sid: $('#promoteid').val() },
                dataType: 'Json',
                success: function (response) {
                    //$('#StudentID').val(response.student);

                    for (var i = 0; i < response.std.length; i++) {
                        $('#StudentID').append("<option value= " + response.std[i].StudentID + ">" + response.std[i].Name + "</option>");
                    }

                    for (var i = 0; i < response.subjects.length; i++) {
                        $('#ClassSubjectID').append("<option value= " + response.subjects[i].ClassSubjectID + ">" + response.subjects[i].Name+"</option>");
                    }
                },
                error: function () {

                }

            });
        });

        $('#ClassSubjectID').change(function () {
             $.ajax({
                url: '@Url.Action("GetTotalMarks", "ExamMarksTables")',
                type: 'GET',
                data: { sid: $('#promoteid').val() },
                dataType: 'Json',
                success: function (response) {
                    $('#StudentID').val(response.StudentID);
                    $('#ClassID').val(response.ClassID);
                    $('#ProgrameID').val(response.ProgrameID);
                },
                error: function () {

                }
            });
        });

    });


</script>
@Scripts.Render("~/bundles/jqueryval")

Views/ExamMarksTables/Delete.cshtml
@model DatabaseAccess.ExamMarksTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ExamMarksTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassSubjectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassSubjectID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalMarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalMarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObtainMarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObtainMarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentTable.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentTable.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExamTable.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamTable.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ExamMarksTables/Details.cshtml
@model DatabaseAccess.ExamMarksTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ExamMarksTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TotalMarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalMarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObtainMarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObtainMarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassSubjectTable.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassSubjectTable.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExamTable.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamTable.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentTable.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentTable.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.FullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MarksID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/ExamMarksTables/Edit.cshtml
@model DatabaseAccess.ExamMarksTable

@{
    ViewBag.Title = "Edit";
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<div class="card mb-4 shadow">
    <div class="card-header"> <h4>Student Tution Fee</h4></div>

    <div class="card-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>ExamMarksTable</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control", @id = "StudentID" })
                        @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <div class="row">
                            <input type="number" class="form-control" placeholder="Enter promote ID" id="promoteid" />

                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="row">
                            <input type="button" class="btn btn-primary" value="Find" id="FindPromoteRecord" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExamID, "ExamID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ExamID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ExamID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ClassSubjectID, "ClassSubjectID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ClassSubjectID", null, htmlAttributes: new { @class = "form-control", @id = "ClassSubjectID" })
                        @Html.ValidationMessageFor(model => model.ClassSubjectID, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalMarks, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TotalMarks, new { htmlAttributes = new { @class = "form-control", @id = "TotalMarks" } })
                        @Html.ValidationMessageFor(model => model.TotalMarks, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ObtainMarks, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ObtainMarks, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ObtainMarks, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {

        $('#FindPromoteRecord').click(function () {
            $('#ClassSubjectID').html('');
            $('#StudentID').html('');
            $.ajax({
                url: '@Url.Action("GetByPromotID", "ExamMarksTables")',
                type: 'GET',
                data: { sid: $('#promoteid').val() },
                dataType: 'Json',
                success: function (response) {
                    //$('#StudentID').val(response.student);

                    for (var i = 0; i < response.std.length; i++) {
                        $('#StudentID').append("<option value= " + response.std[i].StudentID + ">" + response.std[i].Name + "</option>");
                    }

                    for (var i = 0; i < response.subjects.length; i++) {
                        $('#ClassSubjectID').append("<option value= " + response.subjects[i].ClassSubjectID + ">" + response.subjects[i].Name+"</option>");
                    }
                },
                error: function () {

                }

            });
        });

        $('#ClassSubjectID').change(function () {
             $.ajax({
                url: '@Url.Action("GetTotalMarks", "ExamMarksTables")',
                type: 'GET',
                data: { sid: $('#promoteid').val() },
                dataType: 'Json',
                success: function (response) {
                    $('#StudentID').val(response.StudentID);
                    $('#ClassID').val(response.ClassID);
                    $('#ProgrameID').val(response.ProgrameID);
                },
                error: function () {

                }
            });
        });

    });


</script>
@Scripts.Render("~/bundles/jqueryval")

Views/ExamMarksTables/Index.cshtml
@model IEnumerable<DatabaseAccess.ExamMarksTable>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Exam
        </th>
        <th>
            Student
        </th>
        <th>
            Subject
        </th>
        <th>
            Total Marks
        </th>
        <th>
            Obtain Marks
        </th>
        <th>
            User
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ExamTable.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.StudentTable.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ClassSubjectTable.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TotalMarks)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ObtainMarks)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserTable.FullName)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.MarksID }, new { @class = "btn btn-info" })
        @Html.ActionLink("Details", "Details", new { id = item.MarksID }, new { @class = "btn btn-info" })
        @Html.ActionLink("Delete", "Delete", new { id = item.MarksID })
    </td>
</tr>
}

</table>